export const RATE_LIMITER_OPTIONS = Symbol('RATE_LIMITER_OPTIONS');
export const RATE_LIMITER_SKIP = Symbol('RATE_LIMITER_SKIP');
export const RATE_LIMITER_METADATA = Symbol('RATE_LIMITER_METADATA');
